project_id = "sbvkaaywhytxvkcleorj"

[functions.analyze-slides]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-study-plan]
verify_jwt = false

[functions.parse-timetable]
verify_jwt = false

[functions.ai-teach]
verify_jwt = false

[functions.paystack-subscribe]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.analyze-past-questions]
verify_jwt = false
